### PR TITLE
Feature/new timeline chart

### PR DESCRIPTION
**Pull request by urchykli**
Please let me know what needs to be updated.  Thanks!

Here is the static version for reference: https://i2.wp.com/missilethreat.csis.org/wp-content/uploads/2016/10/Missile_Yemen_timeline_v11-01.jpg?w=2400

### CODE REVIEW

**Review by smaraghi — CHANGES_REQUESTED** [review]
@urchykli Thanks for your hard-work Lindsay!

 - [x] Align bars with their respective date objects
- [x] Remove the blue axis-line that underscores the chart
- [ ] Add in y-axis once you drill-down (TBD after discussing with @jnschrag )

Thanks!

**Comment by urchykli** [comment]
Updated chart to remove line under x axis and to align columns with tick marks. Per our discussion, I'm holding off on adding the y axis lines on drilldown.

**Review by smaraghi — CHANGES_REQUESTED** [review]
@urchykli Thanks Lindsay! The alignment is almost there but not quite yet. As you drilldown into the various bars, the date objects are aligned differently. At times they are center aligned, other times they are not and the dates are cut off.

- [x] Resolve x-axis-alignment bug 

Thanks!

**Comment by urchykli** [comment]
I fixed the issue with points being cut off and the x axis not being full width. Thanks!

**Comment by urchykli** [comment]
Changes made based on request from program:
- Remove click to hide functionality from legend
- Remove links from x axis labels
- Links in tooltip
- Change title
- Change subtitle
- Y axis title

**Pull request closed without merging**
